<?php
$receitas = [
    ["id" => 1, "nome" => "Bolo de Chocolate", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Um delicioso bolo de chocolate fofinho.", "imagem" => "https://amogastronomiabrasileira.com.br/wp-content/uploads/2024/02/Bolo-Tentacao-de-Chocolate-com-Morango.jpg"],
    ["id" => 2, "nome" => "Torta de Limão", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Uma torta com creme de limão e merengue.", "imagem" => "https://guiadacozinha.com.br/wp-content/uploads/2018/04/torta-de-limao-facil.jpg"],
    ["id" => 3, "nome" => "Lasanha Bolonhesa", "tipo" => "Salgado", "pais" => "Itália", "descricao" => "Massa com molho à bolonhesa e queijo.", "imagem" => "https://anamariareceitas.com.br/wp-content/uploads/2022/10/Lasanha-a-bolonhesa.jpg"],
    ["id" => 4, "nome" => "Brigadeiro", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Docinho brasileiro feito com leite condensado e chocolate.", "imagem" => "https://www.receitasnestle.com.br/sites/default/files/srh_recipes/1a884bcbc5b04d71476d2995d51d0140.jpg"],
    ["id" => 5, "nome" => "Pizza Margherita", "tipo" => "Salgado", "pais" => "Itália", "descricao" => "Pizza tradicional com molho de tomate, mussarela e manjericão.", "imagem" => "https://cloudfront-us-east-1.images.arcpublishing.com/estadao/YANRMY3TBZGWBCM2UDY6LEZJMA.jpg"],
    ["id" => 6, "nome" => "Churros", "tipo" => "Doce", "pais" => "Espanha", "descricao" => "Massa frita crocante recheada com doce de leite.", "imagem" => "https://hips.hearstapps.com/hmg-prod/images/churros-index-661d4692d05e4.jpg?crop=0.498xw:0.997xh;0.250xw,0.00321xh&resize=1200:*"],
    ["id" => 7, "nome" => "Hambúrguer Artesanal", "tipo" => "Salgado", "pais" => "EUA", "descricao" => "Hambúrguer caseiro suculento com queijo e molho especial.", "imagem" => "https://cdn.casaeculinaria.com/wp-content/uploads/2023/04/05163949/Hamburguer-artesanal.webp"],
    ["id" => 8, "nome" => "Brownie", "tipo" => "Doce", "pais" => "EUA", "descricao" => "Bolo de chocolate denso e úmido.", "imagem" => "https://static.itdg.com.br/images/360-240/5d139b703a9df7604abf863a3bd76aa6/252863-shutterstock-1938293728.jpg"],
    ["id" => 9, "nome" => "Pastel de Carne", "tipo" => "Salgado", "pais" => "Brasil", "descricao" => "Massa frita recheada com queijo ou carne.", "imagem" => "https://s2-receitas.glbimg.com/3MhTZmEn-vxeIGovC29jalC2ctQ=/0x0:653x400/984x0/smart/filters:strip_icc()/s.glbimg.com/po/rc/media/2014/10/28/17_58_29_769_pastel_maria.jpg"],
    ["id" => 10, "nome" => "Coxinha", "tipo" => "Salgado", "pais" => "Brasil", "descricao" => "Salgado recheado com frango e requeijão.", "imagem" => "https://static.itdg.com.br/images/640-440/072bfb16ec52280120ac820e5197ad89/292408-original.jpg"],
    ["id" => 11, "nome" => "Pudim de Leite", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Sobremesa clássica com leite condensado e calda de caramelo.", "imagem" => "https://cozinhaglobo.com.br/wp-content/uploads/2023/07/pudim-de-leite-1024x682.jpg"],
    ["id" => 12, "nome" => "Empada de Frango", "tipo" => "Salgado", "pais" => "Brasil", "descricao" => "Massa amanteigada recheada com frango.", "imagem" => "https://minhasreceitinhas.com.br/wp-content/uploads/2022/08/maxresdefault-50-1024x576.jpg"],
    ["id" => 13, "nome" => "Pão de Queijo", "tipo" => "Salgado", "pais" => "Brasil", "descricao" => "Pão macio feito com queijo e polvilho.", "imagem" => "https://s2-receitas.glbimg.com/nePA5Vc4_EcxwgWSrL5t8t7rHhM=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_e84042ef78cb4708aeebdf1c68c6cbd6/internal_photos/bs/2021/m/T/S329EoTtyBzqB35A5eLA/capa-materia-gshow-2021-12-27t105010.246.png"],
    ["id" => 14, "nome" => "Sorvete de Morango", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Sorvete cremoso de morango natural.", "imagem" => "https://i0.wp.com/canaldareceita.com.br/wp-content/uploads/2024/09/SORVETE-DE-MORANGO.jpg?fit=1000%2C600&ssl=1"],
    ["id" => 15, "nome" => "Bolo de Cenoura", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Bolo fofinho com cobertura de chocolate.", "imagem" => "https://s2-oglobo.glbimg.com/0AbNDoxcuiiOhgfIEb08JaC0bpY=/0x0:1016x684/924x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2023/y/l/qDReaCQpiMpGb2598G7w/bolocenoura.jpg"],
    ["id" => 16, "nome" => "Esfiha de Carne", "tipo" => "Salgado", "pais" => "Oriente Médio", "descricao" => "Massa assada recheada com carne temperada.", "imagem" => "https://s2-receitas.glbimg.com/LkFUI5GpQ-VNswgmn9-pPSm-Cjo=/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_1f540e0b94d8437dbbc39d567a1dee68/internal_photos/bs/2025/6/i/z2mrzpRXSuGOzSUMEjyg/esfiha-de-carne-moida-receita.jpg"],
    ["id" => 17, "nome" => "Canjica", "tipo" => "Doce", "pais" => "Brasil", "descricao" => "Doce de milho branco cozido com leite condensado e coco.", "imagem" => "https://www.comidaereceitas.com.br/wp-content/uploads/2023/09/canjica-1024x684-1-780x521.jpg"],
    ["id" => 18, "nome" => "Macarrão", "tipo" => "Doce", "pais" => "França", "descricao" => "Biscoito delicado e crocante recheado com creme.", "imagem" => "https://pubimg.band.uol.com.br/files/bf59e998cfaf7e690a7e.png"]
];
?>
